#!/bin/bash
echo For you to state your own start and goal functions.
echo -e "\t\t./RUN [[startState] [goalState]]"
echo -e "\t\t./RUN 8 7 6 5 4 3 2 1 0"
echo -e "\t\t./RUN 8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8 0"
java -cp build/classes/ eightslidepuzzle.EightSlidePuzzle $@
